name: Publish to PyPI

on:
  release:
    types: [published]
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+']

jobs:
  build-n-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution to Test PyPI
      if: github.event_name == 'push'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
    - name : Test install from test.pypi.org
      if: github.event_name == 'push'
      run: |
        version=$(grep -Po 'version = "\K[0-9.]*' pyproject.toml)
        pip install -i https://test.pypi.org/simple/ yalafi==${version}
    - name : Test after removing local yalafi folder
      if: github.event_name == 'push'
      run: |
        rm -rf yalafi
        python -c "import yalafi"
        python -c "import yalafi.shell"

    - name: Publish distribution to PyPI
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
